---
title: "HoHoHotSlide Team Tournament"
author: "(by NN Sheep)"
output: 
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      bg: "#FFFFFF"
      fg: "#cd0000" 
      primary: "forestgreen"
      base_font: 
        google: Prompt
      heading_font:
        google: Sen
      code_font:
        google: 
          # arguments to sass::font_google() 
          family: JetBrains Mono
          local: false
    vertical_layout: fill
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(knitr)
library(flexdashboard)
library(RColorBrewer)
library(plotly)
library(kableExtra)
load('Functions.RData')
```

```{r}
# define teams
teams <- tibble(
  `Team Diana`  = c('Diana', 'Big Chungus', 'Yutaaah', 'Larz55', '2much', 'Doodlise'),
  `Team Jon`    = c('JonReremy', 'Jane', 'JSlide', 'Appelpie', 'North', 'Mr.Wood'),
  `Team Mo`     = c('Mo', 'Gimmie Luv', 'Bean', 'Vgamer', 'Gianii', 'Dreeps'),
  `Team Ridge`  = c('Ridge', 'Orion', 'VA-11hall-A', 'Heng', 'Faust', 'Daav'),
  `Team Tattoo` = c('TaTToo', 'KenDan', 'KORA', 'FERYX', 'Ranger Robert', 'Adopt'),
  `Team Zest`   = c('Zest', 'Kalaginho', 'Super7', 'Ant', 'Walter', 'Linsyuanyu'),
)

# import sheet
data <- read_csv('data/v2_xmas_data.csv') %>%
  rename(Name = `In-game name`,
         League = `What is the highest league you have reached?`) %>%
  select(-c(1,3)) %>%
  mutate(across(Ace:Wingman, 
                ~ case_match(., 
                             "Lower than lvl 30 rank S / not unlocked" ~ "NULL",
                             .default = .))) %>%
  mutate(Team = case_match(Name, 
                           teams$`Team Diana` ~ 1,
                           teams$`Team Jon` ~ 2,
                           teams$`Team Mo` ~ 3,
                           teams$`Team Ridge` ~ 4,
                           teams$`Team Tattoo` ~ 5,
                           teams$`Team Zest` ~ 6,
                           ),
         Colour = case_match(Name, 
                           teams$`Team Diana` ~ 'lightgreen',
                           teams$`Team Jon` ~ 'orange',
                           teams$`Team Mo` ~ 'magenta',
                           teams$`Team Ridge` ~ 'gold',
                           teams$`Team Tattoo` ~ 'skyblue',
                           teams$`Team Zest` ~ 'red3',
                           ), .after = 1) %>%
  arrange(Bracket, Team)
```

# Day 1 - Factory

```{r}
# Day 1 matches
top <- c(1,2,3)
bot <- c(4,5,6)
```

```{r}
# read in points per team
day1_raw <- read_csv('data/v2_xmas_results - Day1.csv') 

day1_results <- bind_rows(getResults(day1_raw,1),
                          getResults(day1_raw,2),
                          getResults(day1_raw,3),
                          getResults(day1_raw,4),
                          getResults(day1_raw,5),
                          getResults(day1_raw,6)) 

day1_positions <- day1_results %>%
  mutate(Position = case_match(Points, 
                               3 ~ '(1st)',
                               1 ~ '(2nd)',
                               0 ~ '(3rd)',
                               .default = NULL),
         Points = rep(1:6,6)) %>%
  unite('Player', Position, Player, sep=' ') %>%
  pivot_wider(names_from = Team, values_from = Player) %>%
  select(-Points)

day1_summary <- day1_results %>%
  group_by(Team) %>%
  summarise(Points = sum(Points)) %>%
  arrange(desc(Points)) %>%
  mutate(Rank = 1:6, .before=1)

standings <- arrange(day1_summary,Team) %>%
  arrange(desc(Points)) %>%
  mutate(Rank = 1:6, .before=1)

mvp <- day1_results %>%
  arrange(desc(Points)) %>%
  mutate(Rank = 1:36, Team = NULL, .before=1)
```

```{r}
# match-up decision
top_pick <- tibble(
  Pool = c('Captain', 'Vice Captain', 'Pool 3', 'Pool 4', 'Pool 5', 'Pool 6'),
  Car  = c('SS Maverick','SSS Fang','SSS Kobra','S Wild West','S Kobra','S Taxi')
) %>%
  cbind(day1_positions[,top])

# match-up decision
bot_pick <- tibble(
  Pool = c('Captain', 'Vice Captain', 'Pool 3', 'Pool 4', 'Pool 5', 'Pool 6'),
  Car  = c('S Centaur','SSS Fang','SSS Fang','SS Comet','S Kobra','S Bandit')
) %>%
  cbind(day1_positions[,bot])
```


Column {data-width=450}
--------------
### Top Bracket
```{r}
kable(top_pick) %>%
  kable_styling(bootstrap_options = c("striped", "condensed")) %>%
  column_spec(2, width='3cm', bold = TRUE, color = "white", background = "red3") %>%
  column_spec(1, width='3cm') %>%
  column_spec(3:5, width='4cm')
```
### Bottom Bracket
```{r}
kable(bot_pick) %>%
  kable_styling(bootstrap_options = c("striped", "condensed")) %>%
  column_spec(2, width='3cm',  bold = TRUE, color = "white", background = "red3") %>%
  column_spec(1, width='3cm') %>%
  column_spec(3:5, width='4cm')
```


Column {data-width=125}
--------------
### Day 1 Standings
```{r}
# points table 
knitr::kable(day1_summary, align = c("r", "l")) %>%
  kable_styling(bootstrap_options = c("striped", "condensed"), 
                full_width = F) %>%
  column_spec(2, width='3.5cm',  bold = TRUE, color = "white", background = "red3")
```
### Overall Standings
```{r}
# points table 
knitr::kable(standings, align = c("r", "l")) %>%
  kable_styling(bootstrap_options = c("striped", "condensed"), 
                full_width = F) %>%
  column_spec(2, width='3.5cm',  bold = TRUE, color = "white", background = "red3")
```

Column {data-width=125}
--------------
### MVP Standings
```{r}
# points table 
knitr::kable(mvp, align = c("r", "l")) %>%
  kable_styling(bootstrap_options = c("striped", "condensed"), 
                full_width = F) %>%
  column_spec(2, bold = TRUE, color = "white", background = "red3")
```























```{r}
# Day 2 matches
top <- standings$number[1:3]
bot <- standings$number[4:6]
```

```{r}
# read in points per team
day2_raw <- read_csv('data/v2_xmas_results - Day1.csv') 

day2_results <- bind_rows(getResults(day1_raw,1),
                          getResults(day1_raw,2),
                          getResults(day1_raw,3),
                          getResults(day1_raw,4),
                          getResults(day1_raw,5),
                          getResults(day1_raw,6)) 

day2_positions <- day2_results %>%
  mutate(Position = case_match(Points, 
                               3 ~ '(1st)',
                               1 ~ '(2nd)',
                               0 ~ '(3rd)',
                               .default = NULL),
         Points = rep(1:6,6)) %>%
  unite('Player', Position, Player, sep=' ') %>%
  pivot_wider(names_from = Team, values_from = Player) %>%
  select(-Points)

day2_summary <- day2_results %>%
  group_by(Team) %>%
  summarise(Points = sum(Points)) %>%
  arrange(desc(Points)) %>%
  mutate(Rank = 1:6, .before=1)

standings <- inner_join(standings,select(day2_summary,-Rank),by='Team') %>%
  mutate(Points = Points.x + Points.y) %>%
  select(-Points.x,-Points.y) %>%
  arrange(desc(Points)) %>%
  mutate(Rank = 1:6, .before=1)

mvp <- inner_join(mvp,day1_results,by='Player') %>%
  mutate(Points = Points.x + Points.y) %>%
  select(-Points.x,-Points.y,-Team) %>%
  arrange(desc(Points)) %>%
  mutate(Rank = 1:36, .before=1)
```

```{r}
# match-up decision
top_pick <- tibble(
  Pool = c('Captain', 'Vice Captain', 'Pool 3', 'Pool 4', 'Pool 5', 'Pool 6'),
  Car  = c('SS Maverick','SSS Fang','SSS Kobra','S Wild West','S Kobra','S Taxi')
) %>%
  cbind(day1_positions[,top])

# match-up decision
bot_pick <- tibble(
  Pool = c('Captain', 'Vice Captain', 'Pool 3', 'Pool 4', 'Pool 5', 'Pool 6'),
  Car  = c('S Centaur','SSS Fang','SSS Fang','SS Comet','S Kobra','S Bandit')
) %>%
  cbind(day1_positions[,bot])
```





```{r}
kable(top_pick) %>%
  kable_styling(bootstrap_options = c("striped", "condensed")) %>%
  column_spec(2, width='3cm', bold = TRUE, color = "white", background = "red3") %>%
  column_spec(1, width='3cm') %>%
  column_spec(3:5, width='4cm')
```

```{r}
kable(bot_pick) %>%
  kable_styling(bootstrap_options = c("striped", "condensed")) %>%
  column_spec(2, width='3cm',  bold = TRUE, color = "white", background = "red3") %>%
  column_spec(1, width='3cm') %>%
  column_spec(3:5, width='4cm')
```


```{r}
# points table 
knitr::kable(day1_summary, align = c("r", "l")) %>%
  kable_styling(bootstrap_options = c("striped", "condensed"), 
                full_width = F) %>%
  column_spec(2, width='3.5cm',  bold = TRUE, color = "white", background = "red3")
```

```{r}
# points table 
knitr::kable(standings, align = c("r", "l")) %>%
  kable_styling(bootstrap_options = c("striped", "condensed"), 
                full_width = F) %>%
  column_spec(2, width='3.5cm',  bold = TRUE, color = "white", background = "red3")
```


```{r}
# points table 
knitr::kable(mvp, align = c("r", "l")) %>%
  kable_styling(bootstrap_options = c("striped", "condensed"), 
                full_width = F) %>%
  column_spec(2, bold = TRUE, color = "white", background = "red3")
```










